In [4]:
!pip install pandas
!pip install openpyxl
!pip install matplotlib
!pip install numpy
!pip install scikit-learn
import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_excel(r"C:\Users\Admin\homepricesmultiplevariable.xlsx")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  564000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [5]:
import math
median_bedrooms	= math.floor(df.bedrooms.median())
median_bedrooms

3

In [6]:
df.bedrooms= df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  564000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [ ]:
from sklearn import linear_model
reg= linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

In [9]:
reg.coef_

array([   138.1, -26790. ,  -6870. ])

In [10]:
reg.intercept_

np.float64(384309.9999999997)

In [11]:
reg.predict([[3000,3,40]])

C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([443440.])

In [12]:
138.1*3000+-26790*3+-6870*40+384309.9999999997

443439.9999999997

In [14]:
reg.predict([[2500,4,5]])

C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588050.])