In [1]:
#numpy packages
import numpy as np 

In [3]:
pip install numpy   

Note: you may need to restart the kernel to use updated packages.


In [ ]:
#numerical python==>numpy
#creation of numerical array

In [4]:
arr=np.array([1,2,3])    #creation from the list.... single dimensional
arr


array([1, 2, 3])

In [5]:
arr.shape

(3,)

In [6]:
arr.ndim

1

In [7]:
arr.dtype

dtype('int64')

In [8]:
b=np.array([[2,2,3],[4,5,6]])
b

array([[2, 2, 3],
       [4, 5, 6]])

In [9]:
b.ndim

2

In [10]:
b.dtype

dtype('int64')

In [11]:
b.shape

(2, 3)

In [12]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
c.ndim

2

In [14]:
c.shape

(3, 3)

In [15]:
c.dtype

dtype('int64')

In [16]:
c.size

9

In [17]:
a3 = np.array([
 [[1, 2], [3, 4]],
 [[5, 6], [7, 8]]
])
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
a3.ndim

3

In [19]:
a3.shape

(2, 2, 2)

In [20]:
z=np.zeros((2,3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
o=np.ones((2,3))
o

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
d=np.arange(0,10,2)
d

array([0, 2, 4, 6, 8])

In [25]:
e=np.arange(0,100,7)
e

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [26]:
f=np.linspace(0,10,5)
f

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
g=np.linspace(0,1,10)
g

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [28]:
h=np.eye(3)
h

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
i=np.eye(2)
i

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.zeros((2, 3)) # 2x3 array of zeros
np.ones((2, 2)) # 2x2 array of ones
np.eye(3) # 3x3 identity matrix
np.arange(0, 10, 2) # [0, 2, 4, 6, 8]
np.linspace(0, 1, 5) # 5 values between 0 and 1

In [30]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a

array([1, 2, 3, 4])

In [31]:
b

array([5, 6, 7, 8])

In [35]:
a+b    #elementwise operations

array([ 6,  8, 10, 12])

In [33]:
a*b

array([ 5, 12, 21, 32])

In [34]:
a**2

array([ 1,  4,  9, 16])

In [36]:
#matrix multiply
j=np.dot(a,b)
j

np.int64(70)

In [37]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [38]:
np.dot(a, b) # 1*4 + 2*5 + 3*6 = 32

np.int64(32)

In [39]:
k=np.array([1,2,3,4],dtype=float)
k

array([1., 2., 3., 4.])

In [40]:
k.dtype

dtype('float64')

In [41]:
c=np.array([[3,6,9],[2,5,7]])
d=np.array([[9,3,8],[4,7,9]])
c

array([[3, 6, 9],
       [2, 5, 7]])

In [42]:
d

array([[9, 3, 8],
       [4, 7, 9]])

In [43]:
c+d

array([[12,  9, 17],
       [ 6, 12, 16]])

In [44]:
c*d

array([[27, 18, 72],
       [ 8, 35, 63]])

In [45]:
c**3

array([[ 27, 216, 729],
       [  8, 125, 343]])

In [47]:
v=np.dot(c,d)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [48]:
c.ndim

2

In [49]:
d.ndim

2

In [50]:
c.shape

(2, 3)

In [51]:
d.shape

(2, 3)

In [52]:
d=d.reshape(3,2)
d

array([[9, 3],
       [8, 4],
       [7, 9]])

In [53]:
np.dot(c,d)

array([[138, 114],
       [107,  89]])

In [54]:
a

array([1, 2, 3])

In [56]:
e=a.reshape(3,1)
e

array([[1],
       [2],
       [3]])

In [57]:
np.mean(a)

np.float64(2.0)

In [58]:
np.median(a)

np.float64(2.0)

In [59]:
np.std(a)

np.float64(0.816496580927726)

In [60]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [62]:
a.min()

np.int64(1)

In [63]:
a.max()

np.int64(3)

In [64]:
a.sum()

np.int64(6)

In [65]:
np.unique(a)

array([1, 2, 3])

In [66]:
np.sort(a)

array([1, 2, 3])

In [67]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [68]:
a.mean()

np.float64(2.0)