1. Write a program to reverse a string. Using function and loops 
2. Write a program to check if a string is a palindrome.    madam
3. Create a program to generate Fibonacci series up to n terms. 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, ...
4. Write a program to find all prime numbers up to n.
5. Write a program to remove duplicates from a list. Without set data structure
6. Create a program to find the second largest number in a list
7. Write a program to generate a simple calculator
8. Write a program to read and write to files with error handling.
9. Create a 3D NumPy array of shape (2, 3, 4). Convert it into a 2D array and then flatten it into a 1D array.
10. Create two 2D NumPy arrays (3×2 and 2×3) and perform matrix multiplication using np.dot().


In [58]:
# Write a program to reverse a string. Using function and loops 
def rev_str(str1):
    r = ''
    for i in str1:
        r = i + r
    return r

In [59]:
rev_str('picture')

'erutcip'

In [61]:
 #Write a program to check if a string is a palindrome.    madam
def palindrome(str1):
    if str1==str1[::-1]:
        print(f"{str1} is a palindrome")
    else:
        print(f"{str1} is not a palindrome")

In [62]:
palindrome('hello')

hello is not a palindrome


In [63]:
palindrome("madam")

madam is a palindrome


In [64]:
# Create a program to generate Fibonacci series up to n terms. 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, ...
def fibonacci(n):
    if n<=1:
        return n
    else:
        return fibonacci(n-1)+fibonacci(n-2)


In [65]:
value=int(input('enter a positive value upto which u need fibonacci series'))
for i in range(value):
          print(fibonacci(i),end=',')
    

enter a positive value upto which u need fibonacci series 10


0,1,1,2,3,5,8,13,21,34,

In [53]:
for i in range(10):
    print (fibonacci(i),end=',')


0,1,1,2,3,5,8,13,21,34,

In [5]:
# Write a program to find all prime numbers up to n.
def prime(n):
    x=2
    count=0
    while count<n:
        for i in range(2,int(x**0.5)+1):
            if x%i==0:
                break
            else:
                print(x)
                count+=1
        x+=1

In [6]:
prime(4)

5
7
9
11
11


In [10]:
def prime(n):
    if n<=1:
        return False
    else:
        for i in range(2,int(n**0.5)+1):
            if n%i==0:
                return False
    return True
    

In [11]:
prime(10)

False

In [26]:
def prime_series(a,b):
    prime_list=[]
    for n in range(a,b+1):
        if prime(n):                #calling a function prime()
            prime_list.append(n)
    return prime_list 
    
    


In [27]:
prime_series(0,30)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

In [43]:
# Write a program to remove duplicates from a list. Without set data structure
def remove_duplicates(numbers):
    l=[]
    for i in numbers:
        if i not in l:
            l.append(i)
    return l
    
    

In [44]:
l=[1,2,4,5,1,2,4,5]
remove_duplicates(l)

[1, 2, 4, 5]

In [67]:
 #Create a program to find the second largest number in a list
def sln(numbers):
    l1 = l2 = float('-inf')
    for i in numbers:
        if i>l1:
            l2=l1
            l1=i
        else:
            i>l2 and i!=l1
            l2=i
    print(l2)


In [69]:
l=[1,2,3,4,100,100,99]
sln(l)

99


In [66]:
#Write a program to generate a simple calculator
def add(a,b):
    return a+b
def sub(a,b):
    return a-b
def mul(a,b):
    return a*b
def div(a,b):
    return a/b
print('enter a number to select operation \n'
      ' 1 for addition \n'
      ' 2 for subtraction \n '
      '3 for multiplication \n '
      '4 for division')   
select = int(input("Select operation (1-4): "))
a=int(input('enter 1st number'))
b=int(input('enter 2nd number'))
if select==1:
    print(f'{a} + {b} = {add(a,b)}')
if select==2:
    print(f'{a} - {b} = {sub(a,b)}')
if select==3:
    print(f'{a} + {b} = {mul(a,b)}')
if select==4:
    print(f'{a} + {b} = {div(a,b)}')




enter a number to select operation 
 1 for addition 
 2 for subtraction 
 3 for multiplication 
 4 for division


Select operation (1-4):  1
enter 1st number 2
enter 2nd number 4


2 + 4 = 6


In [2]:
#Write a program to read and write to files with error handling.
try:
    with open ('test.txt','w') as file:   #with operator no need to close
         file.write("hello Devi")
    with open('test.txt','r') as file:
        content = file.read()
        print(content)
except:
    print('error')
else:
    print("done")
finally:
    print('program executed')

hello Devi
done
program executed


In [80]:
#Create a 3D NumPy array of shape (2, 3, 4). Convert it into a 2D array and then flatten it into a 1D array.
import numpy as np
a3d=np.array([
    [[4,3,5,6],[5,6,7,2],[3,4,7,9]],
    [[1,8,9,5],[8,9,5,4],[1,5,8,9]]
             ])
a3d.shape

(2, 3, 4)

In [82]:
#rray_2d = array_3d.reshape(-1, array_3d.shape[-1])
a2d=a3d.reshape(-1,a3d.shape[-1])
a2d



array([[4, 3, 5, 6],
       [5, 6, 7, 2],
       [3, 4, 7, 9],
       [1, 8, 9, 5],
       [8, 9, 5, 4],
       [1, 5, 8, 9]])

In [83]:
a2d.shape

(6, 4)

In [85]:
a2d.ndim

2

In [88]:
a1d=a2d.flatten()
a1d

array([4, 3, 5, 6, 5, 6, 7, 2, 3, 4, 7, 9, 1, 8, 9, 5, 8, 9, 5, 4, 1, 5,
       8, 9])

In [89]:
a1d.ndim

1

In [90]:
a1d.shape

(24,)

In [92]:
#Create two 2D NumPy arrays (3×2 and 2×3) and perform matrix multiplication using np.dot().
a1=np.array([[1,2],
             [3,4],
             [5,6]])
a2=np.array([[1,2,3],
             [4,5,6]])
a1.shape
            

(3, 2)

In [93]:
a2.shape

(2, 3)

In [95]:
a3=np.dot(a1,a2)
a3

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])